# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practice_Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Practice_Swift

    pod ‘Alamofire' # 사용하는 라이브러리들
    pod 'SwiftyJSON'
    pod 'Kingfisher'
    pod 'ObjectMapper'
end
